name: Notify on Issue
on:
  issues:
    types: [opened]
jobs:
  slack-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send message to ms teams
        uses: dhollerbach/github-action-send-message-to-ms-teams@1.0.10
        with:
          webhook: ${{ secrets.MSTEAMS_WEBHOOK }}
          message: 'New Issue ${{github.event.issue.title }} is out, ${{ github.event.issue.html_url }}'