name: Notify on Release
on:
  release:
    types: [published]
jobs:
  slack-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send message to ms teams
        uses: dhollerbach/github-action-send-message-to-ms-teams@1.0.10
        with:
          webhook: ${{ secrets.MSTEAMS_WEBHOOK }}
          message: 'New Release ${{github.event.release.tag_name }} is out, <${{ github.event.release.html_url }}|check it out now.>'